version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TestSamCovidStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dt4bchl9wdyo"
s3_prefix = "TestSamCovidStack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

