AWSTemplateFormatVersion: 2010-09-09
Description: >
  Daily COVID-19 ETL Pipeline Template
Transform: AWS::Serverless-2016-10-31
Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Daily_Covid_Data
  Subscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !GetAtt
        - Function
        - Arn
      Protocol: lambda
      TopicArn: !Ref Topic
    DependsOn:
      - Function
  Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: scripts/
      Runtime: python3.8
      Timeout: 60
      Role: !GetAtt
        - LambdaExecutionRole
        - Arn
      Environment:
        Variables:
          TABLE_NAME: !Select [1, !Split ['/', !GetAtt DynamoDBTable.Arn]]
          NOTIFIER_ARN: !Ref Topic
  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: sns.amazonaws.com
      FunctionName: !GetAtt
        - Function
        - Arn
      SourceArn: !Ref Topic
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:*'
                Effect: Allow
              - Action:
                  - 'sns:Subscribe'
                  - 'sns:Publish'
                  - 'sns:Receive'
                  - 'sns:Unsubscribe'
                Resource: !Ref Topic
                Effect: Allow
              - Action:
                  - 'dynamodb:PutItem'
                Resource: !GetAtt
                  - DynamoDBTable
                  - Arn
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  DailyEvent:
    Type: 'AWS::Events::Rule'
    Properties:
      ScheduleExpression: 'rate(1 minute)'
      Targets:
        - 
          Arn:
            Fn::GetAtt:
              - 'Function'
              - 'Arn'
          Id: 'DailyEventTarget'
  DailyEventPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName:
        Ref: 'Function'
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn:
        Fn::GetAtt:
          - 'DailyEvent'
          - 'Arn'